.TH GNUNET\-NSE 1 "Sep 13, 2014" "GNUnet"

.SH NAME
gnunet\-nse \- Show network size estimates from NSE service.

.SH SYNOPSIS
.B gnunet\-nse
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-nse\fP is a command line tool to show network size estimates from NSE service.

.SH OPTIONS
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
