.TH GNUNET\-SET\-PROFILER 1 "Sep 13, 2014" "GNUnet"

.SH NAME
gnunet\-set\-profiler \- Profiling tool for set.

.SH SYNOPSIS
.B gnunet\-set\-profiler
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-set\-profiler\fP is a command line profiling tool for set.

.SH OPTIONS
.B
.IP "\-A,  \-\-num\-first"
Number of values.
.B
.IP "\-B,  \-\-num\-second"
Number of values.
.B
.IP "\-C,  \-\-num\-common"
Number of values.
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.
.B
.IP "\-x, \-\-operation"
Operation to execute.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
