.TH GNUNET\-SET\-IBF\-PROFILER 1 "Sep 13, 2014" "GNUnet"

.SH NAME
gnunet\-set\-ibf\-profiler \- Profile the invertible bloom filter implementation.

.SH SYNOPSIS
.B gnunet\-set\-ibf\-profiler
.RI [ options ]
.br

.SH DESCRIPTION
\fBgnunet\-set\-ibf\-profiler\fP is a command line tool for profiling the invertible bloom filter implementation.

.SH OPTIONS
.B
.IP "\-A,  \-\-asize"
Number of element in set A-B.
.B
.IP "\-B,  \-\-bsize"
Number of element in set B-A.
.B
.IP "\-C,  \-\-csize"
Number of common elements in A and B.
.B
.IP "\-c FILENAME,  \-\-config=FILENAME"
Use the configuration file FILENAME.
.B
.IP "\-h, \-\-help"
Print short help on options.
.B
.IP "\-k, \-\-hash\-num"
Hash num.
.B
.IP "\-L LOGLEVEL, \-\-loglevel=LOGLEVEL"
Use LOGLEVEL for logging.  Valid values are DEBUG, INFO, WARNING and ERROR.
.B
.IP "\-l LOGFILE, \-\-logfile=LOGFILE"
Configure logging to write logs to LOGFILE.
.B
.IP "\-s, \-\-ibf\-size"
Ibf size.
.B
.IP "\-v, \-\-version"
Print GNUnet version number.

.SH BUGS
Report bugs by using Mantis <https://gnunet.org/bugs/> or by sending electronic mail to <gnunet\-developers@gnu.org>
